// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUX8YTSOfhfmH7_ml3xtDzvy_YYULAPPY',
    appId: '1:832514813710:web:54de3e0e5dcc683c5bb15f',
    messagingSenderId: '832514813710',
    projectId: 'flutter-test-2559d',
    authDomain: 'flutter-test-2559d.firebaseapp.com',
    storageBucket: 'flutter-test-2559d.appspot.com',
    measurementId: 'G-T0HV4GBQ9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmaQ7v2e3UJykiXrLp6UvOKc_g21FclNU',
    appId: '1:832514813710:android:43650b2806255b025bb15f',
    messagingSenderId: '832514813710',
    projectId: 'flutter-test-2559d',
    storageBucket: 'flutter-test-2559d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWBZORcdVy7mw9EBKU_DtRUTTZ3lIPrE',
    appId: '1:832514813710:ios:814e2cc1cc5e70045bb15f',
    messagingSenderId: '832514813710',
    projectId: 'flutter-test-2559d',
    storageBucket: 'flutter-test-2559d.appspot.com',
    iosClientId: '832514813710-5ohv561s699780gbad6ra9fvke8k5pra.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWBZORcdVy7mw9EBKU_DtRUTTZ3lIPrE',
    appId: '1:832514813710:ios:814e2cc1cc5e70045bb15f',
    messagingSenderId: '832514813710',
    projectId: 'flutter-test-2559d',
    storageBucket: 'flutter-test-2559d.appspot.com',
    iosClientId: '832514813710-5ohv561s699780gbad6ra9fvke8k5pra.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crudFirebase',
  );
}
